name: uploadManager
author: tbela99
category: Utilities
tags: [file, upload, html5, ajax]
demo: http://tbela.fragged.org/demos/upload/Demo/
current: 1.4.3.2
sources:
  - "number.js"
  - "Source/progressbar.js"
  - "Source/upload.js"
  - "Source/Languages/Locale.en-US.uploadManager.js"